language: rust
jobs:
  include:
  - rust: nightly
    script: make tests
  - rust: stable
    script: make tests
  - rust: 1.31.0
    install:
      - cargo update
      - cargo update -p pkg-config --precise 0.3.10
      - cargo update -p lazy_static --precise 1.3.0
    script: make tests
