[package]
name = "x11"
version = "0.0.14"
authors = ["Daggerbot <daggerbot@gmail.com>"]
description = "X11 bindings for Rust"
license = "CC0-1.0"
repository = "https://github.com/Daggerbot/x11-rs.git"

[dependencies]
libc = "*"
