// This software is available under the terms of the MIT license.

use std::os::raw::*;

pub type XID = c_ulong;
pub const None: XID = 0;

pub type KeyCode = c_uchar;
pub type Time = c_ulong;

pub type Atom = XID;
pub type Colormap = XID;
pub type Cursor = XID;
pub type Drawable = XID;
pub type Font = XID;
pub type GContext = XID;
pub type KeySym = XID;
pub type Pixmap = XID;
pub type VisualID = XID;
pub type Window = XID;

pub const InputOutput: c_uint = 1;
pub const InputOnly: c_uint = 2;

pub const CWBackPixmap: c_ulong = 1 << 0;
pub const CWBackPixel: c_ulong = 1 << 1;
pub const CWBorderPixmap: c_ulong = 1 << 2;
pub const CWBorderPixel: c_ulong = 1 << 3;
pub const CWBitGravity: c_ulong = 1 << 4;
pub const CWWinGravity: c_ulong = 1 << 5;
pub const CWBackingStore: c_ulong = 1 << 6;
pub const CWBackingPlanes: c_ulong = 1 << 7;
pub const CWBackingPixel: c_ulong = 1 << 8;
pub const CWOverrideRedirect: c_ulong = 1 << 9;
pub const CWSaveUnder: c_ulong = 1 << 10;
pub const CWEventMask: c_ulong = 1 << 11;
pub const CWDontPropagate: c_ulong = 1 << 12;
pub const CWColormap: c_ulong = 1 << 13;
pub const CWCursor: c_ulong = 1 << 14;

pub const NoEventMask: c_long = 0;
pub const KeyPressMask: c_long = 1 << 0;
pub const KeyReleaseMask: c_long = 1 << 1;
pub const ButtonPressMask: c_long = 1 << 2;
pub const ButtonReleaseMask: c_long = 1 << 3;
pub const EnterWindowMask: c_long = 1 << 4;
pub const LeaveWindowMask: c_long = 1 << 5;
pub const PointerMotionMask: c_long = 1 << 6;
pub const PointerMotionHintMask: c_long = 1 << 7;
pub const Button1MotionMask: c_long = 1 << 8;
pub const Button2MotionMask: c_long = 1 << 9;
pub const Button3MotionMask: c_long = 1 << 10;
pub const Button4MotionMask: c_long = 1 << 11;
pub const Button5MotionMask: c_long = 1 << 12;
pub const ButtonMotionMask: c_long = 1 << 13;
pub const KeymapStateMask: c_long = 1 << 14;
pub const ExposureMask: c_long = 1 << 15;
pub const VisibilityChangeMask: c_long = 1 << 16;
pub const StructureNotifyMask: c_long = 1 << 17;
pub const ResizeRedirectMask: c_long = 1 << 18;
pub const SubstructureNotifyMask: c_long = 1 << 19;
pub const SubstructureRedirectMask: c_long = 1 << 20;
pub const FocusChangeMask: c_long = 1 << 21;
pub const PropertyChangeMask: c_long = 1 << 22;
pub const ColormapChangeMask: c_long = 1 << 23;
pub const OwnerGrabButtonMask: c_long = 1 << 24;

pub const KeyPress: c_int = 2;
pub const KeyRelease: c_int = 3;
pub const ButtonPress: c_int = 4;
pub const ButtonRelease: c_int = 5;
pub const MotionNotify: c_int = 6;
pub const EnterNotify: c_int = 7;
pub const LeaveNotify: c_int = 8;
pub const FocusIn: c_int = 9;
pub const FocusOut: c_int = 10;
pub const KeymapNotify: c_int = 11;
pub const Expose: c_int = 12;
pub const GraphicsExpose: c_int = 13;
pub const NoExpose: c_int = 14;
pub const VisibilityNotify: c_int = 15;
pub const CreateNotify: c_int = 16;
pub const DestroyNotify: c_int = 17;
pub const UnmapNotify: c_int = 18;
pub const MapNotify: c_int = 19;
pub const MapRequest: c_int = 20;
pub const ReparentNotify: c_int = 21;
pub const ConfigureNotify: c_int = 22;
pub const ConfigureRequest: c_int = 23;
pub const GravityNotify: c_int = 24;
pub const ResizeRequest: c_int = 25;
pub const CirculateNotify: c_int = 26;
pub const CirculateRequest: c_int = 27;
pub const PropertyNotify: c_int = 28;
pub const SelectionClear: c_int = 29;
pub const SelectionRequest: c_int = 30;
pub const SelectionNotify: c_int = 31;
pub const ColormapNotify: c_int = 32;
pub const ClientMessage: c_int = 33;
pub const MappingNotify: c_int = 34;
pub const GenericEvent: c_int = 35;
pub const LASTEvent: c_int = 36;
